### ISSUE TITLE
Agents refuse to connect to server

### ISSUE THREAD

**Issue by daved0** [roborescue/rcrs-server#63] opened 2022-09-15 05:50 UTC
When I attempt to run the server and launch the sample-agents an error occurs. I've been having trouble figuring out the reason, so any help is greatly appreciated. 
computer: hp
os: ubuntu 20.0.4 virtual machine
java: openjdk version "17.0.4" 2022-07-19
gradle: Gradle 7.5.1
git: git 2.25.1
logs: 
[logs.zip](https://github.com/roborescue/rcrs-server/files/9572210/logs.zip)

![rcrs issues](https://user-images.githubusercontent.com/98972474/190323779-c9a7dc29-4f33-4d71-870b-388422e96149.png)

**Comment by gnardin** [comment] 2022-09-15 06:58
Dear @daved0 ,
I could not reproduce your problem and my environment is similar to yours. The only difference is the Ubuntu version, I use 22.04 but this should not cause any problem. To try reproducing your error, I miss some more information, for instance the command line to launch the `rcrs-server`.

But before sharing more info, please try this sequence of commands in two separate terminals:

**Terminal 1** (Launch Simulation Server)
```
cd rcrs-server
./gradlew completeBuild
cd script
./start.sh -m ../maps/kobe/maps/ -c ../maps/kobe/config/
```
Multiple windows should pop-up, look at the **Kernel GUI** window to see if the Simulators are connected (they should be listed in the right-center of the window and there should be `misc`, `traffic3`, `Collapse`, and `Area Model` connected).

In the panel `Agents with no controller` you should see a list of FIRE_STATION, AMBULANCE_CENTER, POLICE_OFFICE, FIRE_BRUGADE, AMBULANCE_TEAM, and POLICE_FORCE.

Keep all the windows open, do not close them (you can minimize them, if you want).

**Terminal 2** (Launch Sample Agents)
```
cd rcrs-sample-agent-java
./gradlew clean compile
./gradlew launch
```
If it still does not work. Please collect the log files from `rcrs-server` and `rcrs-sample-agent-java` (`logs` directory from both projects).

Please also provide the amount of RAM of your computer.

Kind Regards,
@gnardin

**Comment by daved0** [comment] 2022-09-15 22:18
@gnardin Thank you for the response! Unfortunately, the problem persists, even when I ran those commands. In the server terminal I never got any window pop ups, only the sequence of information telling me what's being generated. Attached is the copy of both log files and some screenshots of my terminal.
Best,
David
[logs (agent).zip](https://github.com/roborescue/rcrs-server/files/9579342/logs.agent.zip)
[logs (server).zip](https://github.com/roborescue/rcrs-server/files/9579343/logs.server.zip)


![rcrs server issue  pt 1](https://user-images.githubusercontent.com/98972474/190518541-fec48b15-237a-4efc-b8dd-c5d9fadc8683.jpg)
![rcrs server issue  pt 3](https://user-images.githubusercontent.com/98972474/190518542-315b93b4-6197-4358-9bf1-6a3be2755fc7.jpg)

**Comment by daved0** [comment] 2022-09-15 22:38
Also my computer has 8gb of total storage, 6gb in use, and 1.5 available.

**Comment by modaresimr** [comment] 2022-09-16 07:14
Thank you for your information.
The connection issue has the following reasons

- [ ] The server is not running
- [ ] Two server is running at the same time
- [ ] Server is running with a different port that your code
- [ ] Your ADF framework is not up to date
- [ ] Your Server is not up to date

Would you please check all of those issues?

**Comment by gnardin** [comment] 2022-09-16 09:49
Dear @daved0 ,
Analyzing the `kernel-out.log` file from the server, I found the following error:
```
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at kernel.StartKernel.main(StartKernel.java:158)
```

Please make sure your `X11 DISPLAY` is properly configured, check possible solutions [here](https://stackoverflow.com/questions/662421/no-x11-display-variable-what-does-it-mean).

**Comment by daved0** [comment] 2022-09-17 05:03
@gnardin @modaresimr I really do appreciate both of your efforts to help me fix this problem, however I can't seem to make any progress. With that being said I'm going to try out a different machine to see if I have any success over there. It's unfortunate but my knowledge with troubleshooting only goes so far and I'm not understanding the root cause. Thanks again for all your help!
[logs (server).zip](https://github.com/roborescue/rcrs-server/files/9590960/logs.server.zip)


![issue](https://user-images.githubusercontent.com/98972474/190841309-cee7dd28-bb7f-4eb9-8beb-e2ea6d34eb25.jpg)

**Comment by gnardin** [comment] 2022-09-17 15:28
Dear @daved0 
Exporting the `DISPLAY` environment variable had some effect since the error changed to
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
	at java.desktop/javax.swing.RepaintManager.<clinit>(RepaintManager.java:247)
	at java.desktop/javax.swing.JComponent.repaint(JComponent.java:4891)
	at java.desktop/java.awt.Component.repaint(Component.java:3405)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:735)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:153)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:129)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:89)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:98)
	at kernel.ui.ComponentManagerGUI.<init>(ComponentManagerGUI.java:32)
	at kernel.ComponentManager.<init>(ComponentManager.java:105)
	at kernel.StartKernel.createKernel(StartKernel.java:270)
	at kernel.StartKernel.main(StartKernel.java:145)
```

Can you please run the commands below to see if fix the issue?

```
sudo apt-get install default-jdk
sudo apt-get install default-jre
```
Then try running the simulator again.

**Comment by daved0** [comment] 2022-09-17 17:22
@gnardin I know it doesn't show but initially I did not have those commands installed.

[logs.zip](https://github.com/roborescue/rcrs-server/files/9592243/logs.zip)


![issue](https://user-images.githubusercontent.com/98972474/190868903-d0a174fd-b3eb-4d21-a4e5-593b49f1ea74.jpg)

**Comment by gnardin** [comment] 2022-09-17 18:26
Dear @daved0 
Installing the Default JRE and JDK did not have any effect. The same error persists and it is probably related to the permission of the GUI to connect to the X server. We have already set the `export DISPLAY=:0` to direct any graphical interface to the monitor 0 (default monitor), but there is still something blocking the GUI to access the X server.

Try installing the xorg

```
sudo apt-get update 
sudo apt-get upgrade
sudo apt-get install xserver-xorg-core xserver-xorg xorg
```
then, allow the simulator to connect to the X server using the X utility called `xhost`.To allow all local connections:

```
xhost +local:
```

**Comment by daved0** [comment] 2022-09-18 06:23
@gnardin Is there a chance firewalls could be an issue, because Windows Defender Firewall is currently active
![issue](https://user-images.githubusercontent.com/98972474/190888624-c99e91f9-be00-4ac7-afcf-de5c1af6b9aa.jpg)

**Comment by gnardin** [comment] 2022-09-19 06:33
Dear @daved0 
I did not see that you are running Ubuntu in a Virtual Machine. I just realized it when you asked about disabling the Windows Firewall. Anyway, I do not think that Windows Firewall is causing any issue because the simulator does not require any resource for the Internet or outside the VM to start.

I somehow reproduced your environment using Ubuntu in VirtualBox, but in using Ubuntu as my main OS. I was able to install the server and run it without much problem.

After installing Ubuntu, I installed the [VirtualBox Guest Additions](https://www.virtualbox.org/manual/ch04.html#guestadd-install), `git`, `openjdk-17-jre`, `openjdk-17-jdk`, `gradle`, and `xterm`. It is important to install `xterm` because the `rcrs-server` scripts use this application to launch the graphical interfaces.

If you use a different Virtual Machine application, check if there is any restriction with respect to Graphical Interface in their configuration.

**Comment by daved0** [comment] 2022-09-23 07:03
@gnardin Sorry for the delayed response I couldn't get a chance to respond, however I do come with good news. Long story short, I used GIT BASH instead of Linux shell and everything seemed to run smoothly. I appreciate all your work to help me fix this issue and giving me clear cut instructions! 

![success](https://user-images.githubusercontent.com/98972474/191907701-f0e88179-7862-4406-a8b8-ad413c1d8577.jpg)

**Comment by gnardin** [comment] 2022-09-23 07:07
@daved0 
Excellent news! I will close this issue.
Please open another issue in case you run into any problems or have any questions.

**Closed by gnardin** 2022-09-23 07:07 UTC
Labels: question
